### ISSUE TITLE
error with giscus when using Next.js v14.1.0 

### ISSUE THREAD

**Issue by tifandotme** [tifandotme/tifan.me#10]
Discussion: https://github.com/giscus/giscus-component/issues/1976

**Comment by shenlu89** [comment]
Hi, see you again. Remember me? You have given me some suggestions before. https://github.com/shenlu89/shenlu.me/issues/3#issue-1819737086

I got a hack way to solve this issue.

https://github.com/giscus/giscus-component/issues/1976#issuecomment-1937429577

**Comment by tifandotme** [comment]
> Hi, see you again. Remember me? You have given me some suggestions before. [shenlu89/shenlu.me#3 (comment)](https://github.com/shenlu89/shenlu.me/issues/3#issue-1819737086)
> 
> I got a hack way to solve this issue.
> 
> [giscus/giscus-component#1976 (comment)](https://github.com/giscus/giscus-component/issues/1976#issuecomment-1937429577)

https://github.com/shenlu89/shenlu.me/commit/74cb9b75f5a0022b2d88c0014152df1709e527d4#diff-d3a29a9b14e6921438a2e83dfb261e2fec2b6f85fc112991ba63a59b80095039

I see that you moved the library to a local file and added a @ts-ignore directive to it? That's actually clever and straightforward. I might try this. Thank you
